Alaurent/better email confirm form
gip-inclusion/inclusion-connect pull request #177
Opened 2023-06-26 09:20 UTC by tonial

**Carte Notion : ** https://www.notion.so/plateforme-inclusion/Je-demande-le-renvoi-d-un-email-alors-qu-email-valid-cran-bug-ad1ccf61d94745e49a23ac34e3591ce4

### Pourquoi ?

Gestion plus souple des erreurs du formulaire de renvois d'email de confirmation:
Si on ne trouve pas l'email à confirmer, on redirige vers l'espace personnel en indiquant que l'email est déjà validé. 

Meilleur gestion du bouton de redirection vers le partenaire en conservant le lien en session 

### Comment 

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran

2023-06-26 12:16 UTC, francoisfreitag requested changes
> his allows us to keep the button displayed even when refreshing the
confirm-email page

Ce cas est déjà géré, le paramètre de l’URL est préservé sur un refresh.

> opening the verification link when the email was
already verified

La vérification de l’email nettoie la session (puisqu’elle cause un login), et donc on n’aura pas accès au `referrer_uri`.

Je me demande si le bon fix ne serait pas de rajouter referrer_uri à https://github.com/gip-inclusion/inclusion-connect/pull/139/files#diff-5dff6915f0f7137772cd885da8cce8f52712963c2c4c8357a46399df81a23a3cR12 ?

2023-06-26 12:16 UTC, francoisfreitag commented on inclusion_connect/accounts/views.py
> +    return HttpResponseRedirect(referrer_uri)
Ça revient au même, mais évite la négation.
```suggestion
    if referrer_uri:
        return HttpResponseRedirect(referrer_uri)
    return Http404
```

2023-06-26 12:16 UTC, francoisfreitag commented on inclusion_connect/accounts/views.py
> +            return verified_email_redirect(request)
Si l’email a confirmé a disparu, on ne peut pas dire à l’utilisateur que son email est déjà vérifié, on ne sait pas quel est son email.

2023-06-26 12:43 UTC, tonial commented
>>  This allows us to keep the button displayed even when refreshing the confirm-email page
>
> Ce cas est déjà géré, le paramètre de l’URL est préservé sur un refresh.

De ce que j'ai constaté, ça ne fonctionne pas toujours. Le cas de figure est : 
- j'ai un onglet / navigateur ouvert sur confirm-email (pas de paramètres dans l'url car stocké dans `user.next_redirect_uri`)
- j'ouvre le lien dans un autre onglet/navigateur : `user.next_redirect_uri` est consommé
- quand je rafraîchi l'onglet confirm-email : pas de 404 grâce au 1er commit de la PR, par contre referrer_uri est perdu.

Maintenant, il est quand même accessible

>> opening the verification link when the email was already verified
>
> La vérification de l’email nettoie la session (puisqu’elle cause un login), et donc on n’aura pas accès au referrer_uri.

La session est vide, mais comme on est redirigé sur `user.next_redirect_uri` qui contient à nouveau `referrer_uri`, on le récupère et le remet en session.  

> Je me demande si le bon fix ne serait pas de rajouter referrer_uri à https://github.com/gip-inclusion/inclusion-connect/pull/139/files#diff-5dff6915f0f7137772cd885da8cce8f52712963c2c4c8357a46399df81a23a3cR12 ?

Ah, il faut renommer `redirect_uri` en `referrer_uri`à cet endroit pour que ça marche avec l'erreur CSRF.
Par contre, ça ne marchera pas pour le refresh, si ?

2023-06-26 12:43 UTC, tonial commented on inclusion_connect/accounts/views.py
> +            return verified_email_redirect(request)
Tu suggères de juste le renvoyer sur la page de compte perso ?

2023-07-03 15:17 UTC, francoisfreitag commented
Vu avec Antoine, le redirect vers edit_user_info est probablement plus utile que la 404, donc sans message qui pourrait causer une confusion, c’est une amélioration.

Antoine va mettre à jour le code pour retirer la vue `return_to_referrer`, la remplaçant par une préservation du `referrer_uri` lors de la navigation (e.g. l’utilisateur vient changer son email, au lieu de l’emmener sur `email-confirm-view`, on l’emmène sur `email-confirm-view?referrer_uri=...`.

2023-07-04 09:33 UTC, francoisfreitag approved these changes
Autrement, parfait !

2023-07-04 09:36 UTC, tonial commented on inclusion_connect/accounts/views.py
> +            return HttpResponseRedirect(add_url_params(reverse("accounts:confirm-email"), self.request.GET.dict()))
Cool, je connaissais pas :)

2023-07-04 09:41 UTC, tonial commented on inclusion_connect/accounts/views.py
> +            return HttpResponseRedirect(add_url_params(reverse("accounts:confirm-email"), self.request.GET.dict()))
Il faut rajouter le `"?"` entre les deux aussi

2023-07-04 09:42 UTC, merged

2023-07-04 10:35 UTC, francoisfreitag commented on inclusion_connect/accounts/views.py
> +            return HttpResponseRedirect(add_url_params(reverse("accounts:confirm-email"), self.request.GET.dict()))
Exact :+1: