docs: Update dev docs
gip-inclusion/inclusion-connect pull request #290
Opened 2023-09-26 13:14 UTC by vjousse

### Pourquoi ?

Lors de l'installation du projet à partir de 0, il est actuellement compliqué de comprendre les pré-requis nécessaires (venv, utilisation de make ou pas, etc).

### Comment

On clarifie la doc en la transformant en un tutoriel « pas à pas ».

2023-09-26 13:45 UTC, tonial requested changes
C'est en effet beaucoup mieux.
Je te laisse regarder mes quelques remarques.

2023-09-26 13:45 UTC, tonial commented on docs/development.md
> +make virtualenv
make venv

2023-09-26 13:45 UTC, tonial commented on docs/development.md
> +Il faudra utiliser le couple `local_inclusion_connect`/`password` pour se connecter avec un client OpenID Connect.
je mettrais plutôt ici la configuration des redirect_uris (après avoir lancé runserver + avoir donné les crédentials de l'admin).

Cette ligne peut remplacer ou être remplacer par la note située après la mention de la configuration des redirect_uris

2023-09-26 13:45 UTC, tonial commented on docs/development.md
> +## Lancer le serveur de développement
Cette étape ne pourra pas fonctionner sans avoir lancé docker-compose.
Peut être ajouter une étape `## Lancer les composant applicatifs` disant de lancer `docker compose up` suivi d'un lien vers l'explication en bas du fichier ?

2023-09-26 14:03 UTC, francoisfreitag reviewed
Merci d’être passé sur l’onboarding, c’est sûr qu’entre deux devs des emplois, le projet est assez orienté emplois. :+1:

2023-09-26 14:03 UTC, francoisfreitag commented on docs/development.md
> +NB : le port exposé est le `5433` car si vous travaillez déjà avec un PSQL, il est probable que votre port `5432` soit déjà utilisé.
On pourrait peut-être documenter les variables d’environnement pour un éventuel `direnv` ?

2023-09-26 14:30 UTC, vjousse commented on docs/development.md
> +Avant chaque commande python/django, il sera primordial d'avoir activé votre environnement virtuel au préalable via la commande suivante (dans le répertoire du projet) :
Avant chaque commande python, il est nécessaire d'avoir un venv d'activé. Comment ça pourrait ne pas être le cas ? (je ne parle pas des commandes make)

2023-09-26 14:48 UTC, vjousse commented on docs/development.md
> +### Activer l'environnement virtuel
Je suis relativement sans avis pour `direnv`, j'aime bien laisser aux gens le choix de gérer leurs `env`, `venv` comme ils veulent.

2023-09-26 15:03 UTC, francoisfreitag commented on docs/development.md
> +Avant chaque commande python/django, il sera primordial d'avoir activé votre environnement virtuel au préalable via la commande suivante (dans le répertoire du projet) :
Activer le venv est valide pour le shell en cours, la suite de commande suivante devrait passer dans ton shell:

```sh
$ . .venv/bin/activate
$ ./manage.py collectstatic
$ ./manage.py createsuperuser
$ ./manage.py runserver
# ...
```

Il n’y a donc pas besoin de réactiver le venv entre chaque commande, ce que la formulation actuelle peut laisser penser.

2023-09-26 15:17 UTC, francoisfreitag commented on docs/development.md
> +### La commande `make venv`
Le but des commandes `make` est de fournir quelques recettes “clé en main” qui fonctionnent, pour éviter trop d’étapes. Je suis d’accord que la syntaxe Makefile est assez déroutante, et il faut s’y pencher pour bien comprendre ce qu’il se passe.

Un guide d’installation plus “manuel” me convient également, tant qu’il n’y a pas d’embranchements. La suite de commande `python -m venv .venv && . .venv/bin/activate && pip install -r requirements.dev.txt` est suffisamment simple. :shrug:

2023-09-26 15:18 UTC, francoisfreitag commented on docs/development.md
> +NB : le port exposé est le `5433` car si vous travaillez déjà avec un PSQL, il est probable que votre port `5432` soit déjà utilisé.
Pour moi, l’idée est qu’à la fin de `development.md`, le développeur a sous la main un environnement fonctionnel. Donc la configuration des variables d’environnements mérite une section. Après, avec ou sans `direnv` :shrug:

2023-09-26 15:34 UTC, francoisfreitag commented on docs/development.md
> +### La commande `make venv`
Petits trucs sympa en faveur du `make` :
- l’appel à `pip-sync`, inutile au début, mais au cours de la vie du projet, permet de synchroniser les dépendances avec la spec
- la compatibilité mac/linux.

2023-09-27 08:48 UTC, vjousse commented on docs/development.md
> +### La commande `make venv`
J'ai modifié le README en ce sens

2023-09-27 08:49 UTC, vjousse commented on docs/development.md
> +Avant chaque commande python/django, il sera primordial d'avoir activé votre environnement virtuel au préalable via la commande suivante (dans le répertoire du projet) :
J'ai modifié le wording

2023-09-27 08:56 UTC, francoisfreitag reviewed
Autrement, ça m’a l’air top !

2023-09-27 08:56 UTC, francoisfreitag commented on docs/development.md
> +Avant chaque commande python/django, assurez-vous d'avoir un environnement virtuel d'activé au préalable. Pour activer un environnement virtuel pour le shell courant, lancez la commande suivante :
```suggestion
Avant de lancer une commande python/django, assurez-vous d'avoir un environnement virtuel d'activé. Pour activer un environnement virtuel pour le shell courant, lancez la commande suivante :
```

2023-09-27 08:56 UTC, francoisfreitag commented on docs/development.md
> +NB : le port exposé est le `5433` car si vous travaillez déjà avec un PSQL, il est probable que votre port `5432` soit déjà utilisé.
Il faudrait peut-être bouger cette section (composants applicatifs) avant d’appeler `migrate` (voir avant la construction du venv), autrement `migrate` échouera.

2023-09-27 08:57 UTC, vjousse commented on docs/development.md
> +NB : le port exposé est le `5433` car si vous travaillez déjà avec un PSQL, il est probable que votre port `5432` soit déjà utilisé.
J'ai documenté les variables d'env pour modifier le port de PG

2023-09-27 09:00 UTC, vjousse commented on docs/development.md
> +Il vous faudra alors modifier la variable d'environnement `PGPORT` en conséquence pour que votre application Django se connecte sur le bon port.
Ça ne me choque pas de garder le `5433` car en effet on a souvent un PG qui tourne sur le `5432` et avec le setup actuel, ya plus de chance que ça _fonctionne du premier coup_.

2023-09-27 09:00 UTC, vjousse commented on docs/development.md
> +NB : le port exposé est le `5433` car si vous travaillez déjà avec un PSQL, il est probable que votre port `5432` soit déjà utilisé.
Tu crois ? Vu que le docker-compose est documenté avant, le migrate n'échouera pas, non ? (sauf souci de port)

2023-09-27 09:22 UTC, francoisfreitag commented on docs/development.md
> +Il vous faudra alors modifier la variable d'environnement `PGPORT` en conséquence pour que votre application Django se connecte sur le bon port.
Si on garde le `5433`, je pense qu’il faudrait documenter l’histoire du port avant migrate, autrement c’est sûr que postgres échouera (sauf si l’utilisateur utilise la connexion via socket UNIX) ?

2023-09-27 09:23 UTC, francoisfreitag commented on docs/development.md
> +NB : le port exposé est le `5433` car si vous travaillez déjà avec un PSQL, il est probable que votre port `5432` soit déjà utilisé.
Ah oui, je l’avais loupé celui là :+1:

2023-09-27 11:18 UTC, tonial approved these changes

2023-09-27 12:02 UTC, merged

2023-09-29 12:00 UTC, tonial commented
J'ai oublié de te préciser de squasher les commits.

Je me suis permis de le faire directement sur master.

Quand ce sont des gros commits, ou des changements plutôt distincts d'une grosse PR, on a tendance à les laissé séparés, mais pour le coup, sur des modifications successives d'un même fichier de documentation, je trouve cela plus propre et plus simple à relire de les regrouper en un.