Ajout de l'icone pour afficher le mot de passe saisi
gip-inclusion/inclusion-connect pull request #7
Opened 2023-04-24 07:45 UTC by tonial

https://www.notion.so/plateforme-inclusion/Refonte-Permettre-l-utilisateur-de-visualiser-le-mot-de-passe-tap-507107cafffd47b9bc9ae38b56b42c5c?pvs=4

### Pourquoi ?

Éviter les demande d'aide au support

### Comment 

Attirer l'attention sur les décisions d'architecture ou de conception importantes.

### Captures d'écran

2023-04-24 10:01 UTC, francoisfreitag requested changes
Il manque le name sur les `input`.

On ne devrait pas aussi utilise `bootstrap-fields` pour faire le rendu ?

2023-04-24 12:02 UTC, tonial commented on inclusion_connect/static/js/prevent_multiple_submit.js
> +  $('form.js-prevent-multiple-submit').on('submit', function () {
Excellent idée.

Sauf que c'est une dépendance nécessaire du thème :(

2023-04-24 12:04 UTC, tonial commented on inclusion_connect/templates/login.html
> +                        <label for="id_password">Mot de passe *</label>
:+1:

2023-04-24 16:10 UTC, francoisfreitag commented
Plutôt que de dupliquer le markup (ce qui n’est accessoirement pas facile à utiliser), je te propose de définir un template tag maison. (voir commit [Use a custom template tag](https://github.com/gip-inclusion/inclusion-connect/pull/7/commits/6bea4c15c1bc7f6a637c35ad09e0283250cc6a90))

2023-04-25 08:52 UTC, merged

2023-04-25 08:53 UTC, tonial commented
J'ai mergé vu que tu as écrit le commit que tu demandais :D