Faciliter l’installation du projet et le simplifier
gip-inclusion/inclusion-connect pull request #9
Opened 2023-04-24 12:50 UTC by francoisfreitag

### Pourquoi ?

- Avoir une procédure unique, documentée pour développer sur le projet
- Simplifier l’architecture (utilisation de postgres, enlever le docker Django)
- S’assurer qu’une version conforme à la spécification est utilisée pour les dépendances
- Sécuriser (éviter d’écouter le monde entier)

2023-04-24 12:59 UTC, tonial requested changes
Merci pour ce chouette nettoyage !

2023-04-24 12:59 UTC, tonial commented on Makefile
>  VIRTUAL_ENV ?= .venv
tu as mis itou_django dans le nom de commit :)

2023-04-24 12:59 UTC, tonial commented on DEVELOPING.md
> +## Direnv (optionnel)
Ce serait plutot à mettre dans https://github.com/gip-inclusion/inclusion-connect/blob/main/docs/development.md

2023-04-24 12:59 UTC, tonial commented on DEVELOPING.md
> +MailHog is an email testing tool for developers:
en français plutot ?

2023-04-24 12:59 UTC, tonial commented on docker-compose.yml
>    postgres_data:
Je crois qu'on n'a plus besoin du volume postgres_data_backups en retirant les scripts de backup

2023-04-24 13:55 UTC, francoisfreitag commented on Makefile
>  VIRTUAL_ENV ?= .venv
Oopsie, transition en cours :stuck_out_tongue:

2023-04-24 14:03 UTC, francoisfreitag commented on docker-compose.yml
>    postgres_data:
Bien vu !

2023-04-24 14:04 UTC, francoisfreitag commented on DEVELOPING.md
> +MailHog is an email testing tool for developers:
Je vais faire une PR pour connecter MailHog :)

2023-04-24 14:04 UTC, francoisfreitag commented on DEVELOPING.md
> +## Direnv (optionnel)
Ahh, super ! Je viens de fusionner les deux documents (en gardant majoritairement l’existant).

2023-04-24 14:08 UTC, tonial approved these changes
LGTM

2023-04-24 14:08 UTC, tonial commented on docs/development.md
>  ## Lancer le service en local
Peut être renommer cette section vu qu'on ne lance plus que docker et mailhog à cette étape (mais j'ai aucune inspiration à proposer)

2023-04-24 14:28 UTC, francoisfreitag commented on docs/development.md
>  ## Lancer le service en local
Suggestion dans [fixup! Update docs/development.md](https://github.com/gip-inclusion/inclusion-connect/pull/9/commits/de6a71a625176e48774200efca555d2c7b879332) :)

2023-04-24 14:54 UTC, francoisfreitag commented on DEVELOPING.md
> +MailHog is an email testing tool for developers:
#11

2023-04-24 15:03 UTC, tonial approved these changes

2023-04-24 15:03 UTC, tonial commented on docs/development.md
>  ## Lancer le service en local
excellent inspiration :D

2023-04-25 07:18 UTC, tonial commented on docs/development.md
>  docker-compose up
tu peux remplacer par `docker compose` au passage.

2023-04-25 07:32 UTC, merged